#!/usr/bin/env python
# -*- coding: utf-8 -*-

import awsm
from datetime import datetime
import sys

def run():
    start = datetime.now()

    configFile = '/code/awsm/test_data/RME_run/AWSM_test_config_ipysnobal.ini'
    if len(sys.argv) > 1:
        configFile = sys.argv[1]


    #===============================================================================
    # Initialize and run basin
    #===============================================================================
    #

    # 1. initialize
    # try:
    with awsm.framework.framework.AWSM(configFile) as a:

        if not a.do_wrf:
            if not a.config['isnobal restart']['restart_crash']:
            # distribute data by running smrf
                if a.do_smrf:
                    a.runSmrf()

                # convert smrf output to ipw for iSnobal
                if a.do_make_in:
                    a.nc2ipw('smrf')

                if a.do_isnobal:
                    # run iSnobal
                    a.run_isnobal()

                elif a.do_ipysnobal:
                    # run iPySnobal
                    a.run_ipysnobal()

                    # convert ipw back to netcdf for processing
                if a.do_make_nc:
                    a.ipw2nc('smrf')
            # if restart
            else:
                if a.do_isnobal:
                    # restart iSnobal from crash
                    a.restart_crash_image()
                    # convert ipw back to netcdf for processing
                elif a.do_ipysnobal:
                    # run iPySnobal
                    a.run_ipysnobal()

                if a.do_make_nc:
                    a.ipw2nc('smrf')

        # perform same operations using gridded WRF data
        elif a.do_wrf:
            if a.do_smrf:
                a.runSmrf_wrf()

            if a.do_make_in:
                a.nc2ipw('wrf')

            if a.do_isnobal:
                a.run_isnobal_forecast()

            if a.do_make_nc:
                a.ipw2nc('wrf')

        # Run iPySnobal from SMRF in memory
        if a.do_smrf_ipysnobal:
            a.run_smrf_ipysnobal()

        a._logger.info('AWSM finished in: {}'.format(datetime.now() - start) )

if __name__ =='__main__':
    run()
