#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import argparse
import seaborn as sns
from smrf import ipw


def run():

    parser = argparse.ArgumentParser(description='Plotting an ipw image')
    parser.add_argument('fp', metavar='F', type=str,
                        help='Path to ipw file')
    parser.add_argument('--band', metavar='-B', type=int, default=0,
                        help='band to plot')

    args = parser.parse_args()

    fp = args.fp
    b = args.band

    print('Plotting [{}] band {}!'.format(fp,b))

    if os.path.isfile(args.fp):
        plot_ipw_band(fp, b)

    else:
        raise IOError('File does not exist.')


def plot_ipw_band(fp, b):
    """
    Plot station data, filtering by dates if necessary
    Args:
        fp - file pointer
        b - band of ipw to plot
    """

    # read in data
    i = ipw.IPW(fp)
    data = i.bands[b].data

    # some formatting
    sns.set_context("poster")
    #sns.set_style("dark")

    # show what file is being plotted
    title = os.path.basename(fp)
    title = 'Plotting file: ' + title
    plt.title(title)
    plt.imshow(data)
    # plot
    plt.show()


if __name__ == '__main__':
    run()
