#!/usr/bin/env bash

# A script to create the gold files needed for SMRF
# Run this script in the main smrf directory, the config
# file will put the outputs in the correct place
#
# Run as:
#     $ ./awsm/tests/basins/RME/gold/make_gold_stations

read -r -p "Recreating gold standard, are you sure? [y/N] " response
if [[ "$response" = "yes" || "$response" = "y" ]]
then
    echo "Updating RME station gold files"
    echo "Removing old gold files"
    rm awsm/tests/basins/RME/gold/*.nc
    
    echo "Running AWSM"
    awsm awsm/tests/basins/RME/gold/gold_config.ini

    echo "Cleaning up"
    mv awsm/tests/basins/RME/gold/rme/wy1986/rme_test/run19860217_19860217/ipysnobal.nc awsm/tests/basins/RME/gold/
    rm -r awsm/tests/basins/RME/gold/rme/
else
    echo "RME station gold files not updated"
fi

